### ISSUE TITLE
Fail to load on startup

### ISSUE THREAD

**Issue by Space-Coder** [davidegiacometti/PowerToys-Run-VisualStudio#3]
### PowerToys (Preview) v0.75.1
![image](https://github.com/davidegiacometti/PowerToys-Run-VisualStudio/assets/20099119/09b6a291-b563-4a74-b611-3b4211afb29e)

The plugin failed to load, any solutions?

Attaching log file if it help
[2023-11-14.txt](https://github.com/davidegiacometti/PowerToys-Run-VisualStudio/files/13349376/2023-11-14.txt)

**Comment by davidegiacometti** [comment]
Hi @Space-Coder 
Are you using the latest version of the plugin?
You must upgrade to [0.1.0](https://github.com/davidegiacometti/PowerToys-Run-VisualStudio/releases/tag/0.1.0) with PowerToys 0.75.1 since that version introduced a breaking change.

**Comment by Space-Coder** [comment]
Hi @davidegiacometti !
Yeah, i'm using latest version of plugin.
Also, i'm trying to compile plugin from source, and use it, but there no effect and i still receive this error.

**Comment by davidegiacometti** [comment]
This is the error from the log file...

`[2023-11-14 16:34:47.8418] [ERROR] [C:\a\_work\1\s\src\modules\launcher\Wox.Plugin\PluginPair.cs::178]
Can't validate plugin ID of plugin <Visual Studio> in C:\Users\Zhehzdryn\AppData\Local\PowerToys\RunPlugins\VisualStudio\Community.PowerToys.Run.Plugin.VisualStudio.dll: The static property <Main.PluginID> was not found.
`

...and this is supposed to be fixed in 0.1.0.
Can you double check the version on the file properties `C:\Users\Zhehzdryn\AppData\Local\PowerToys\RunPlugins\VisualStudio\Community.PowerToys.Run.Plugin.VisualStudio.dll`

![image](https://github.com/davidegiacometti/PowerToys-Run-VisualStudio/assets/25966642/1bb3ad21-6ab4-44bd-b540-c5d771d38685)

**Comment by Space-Coder** [comment]
Version 0.1.0
![image](https://github.com/davidegiacometti/PowerToys-Run-VisualStudio/assets/20099119/198ca523-8512-402d-b4cf-2b144f237512)

**Comment by davidegiacometti** [comment]
Any chance that there is an older version of Visual Studio plugin in one of this paths?
- `C:\Users\Zhehzdryn\AppData\Local\PowerToys\RunPlugins`
- `C:\Users\Zhehzdryn\AppData\Local\Microsoft\PowerToys\PowerToys Run\Plugins`

**Comment by Space-Coder** [comment]
Oh, you are right! I found older version in this path:
* `C:\Users\Zhehzdryn\AppData\Local\PowerToys\RunPlugins`

My fault. 
Thank you for help !

**Comment by davidegiacometti** [comment]
No problem, glad you solved! 😃
